#!/bin/bash

# Build script for project.black kernel
# by wlkmanist

KERNEL_DIR=$PWD
IMAGE=$KERNEL_DIR/arch/arm/boot/zImage-dtb
RDY_SCRIPT=$KERNEL_DIR/../Dev/copy_boot.sh
BUILD_START=$(date +"%s")
VERSION=$2
PARAM=$1

export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=/mnt/Data/tools/linaro-cortex-toolchains/arm-cortex_a15-linux-gnueabihf-linaro_4.7.4-2014.04/bin/arm-cortex_a15-linux-gnueabihf-

case "$PARAM" in
  "")
  ;;
  "def")
    make black_wlk_defconfig
  ;;
  "dbg")
    make black_wlk_dbg_defconfig
  ;;
  "cln")
    make clean
  ;;
  "rdy")
    if [ -z "$VERSION" ]; then
	echo "Usage: ./build rdy [version letter]"
	exit -1
    fi
  ;;
  "--help" | * )
    echo "Usage: ./build [param (optional)]"
    echo ""
    echo "Params:"
    echo "  [none]: build only"
    echo "  def   : build with main defconfig"
    echo "  dbg   : build with debug defconfig"
    echo "  cln   : make clean and build"
    echo "  rdy   : build only then export"
    echo "  --help: display this"

    exit 0
  ;;
esac
[ $? -eq 0 ]  || exit -1

make -j$(nproc --all)
[ $? -eq 0 ]  || exit -1

BUILD_END=$(date +"%s")
TIME_DIFF=$(($BUILD_END - $BUILD_START))

echo ""
echo -e "Build time: $((TIME_DIFF / 60))m $((TIME_DIFF % 60))s."
echo ""

if [ "$PARAM" = "rdy" ]; then
	$RDY_SCRIPT $VERSION $IMAGE
fi

